### ISSUE TITLE
Error while attempting to retrieve provider lease status

### ISSUE THREAD

**Issue by blockTokenTech** [tombeynon/akash-deploy#3]
Hi there,

Thanks for this amazing tool. I've used it to create a deployment offer and  I then tried to create a lease for the bid on it which resulted in an error, and whenever I try to view the list of deployments I get an error.

lib/akash/cli.rb:56:in `run'
lib/akash/cli.rb:45:in `cmd'
lib/akash/cli.rb:40:in `cmd_json'
lib/akash/lease.rb:110:in `status_data'
lib/akash/lease.rb:78:in `services'
lib/akash/lease.rb:68:in `uris'
lib/akash/deployment.rb:65:in `uris'
app/views/dashboard/show.html.erb:29:in `block in _app_views_dashboard_show_html_erb__3437874297774432222_69940740302820'

The code successfully calls `akash query market lease list`

It then runs

``` akash provider lease-status --from deploy --dseq 430388 --oseq 1 --gseq 1 --provider akash10cl5rm0cqnpj45knzakpa4cnvn5amzwp4lhcal --home /root/akash --keyring-backend file --node http://135.181.60.250:26657```

Which gives an error of `Error: Get "https://provider.sjc1p0.mainnet.akashian.io:8443/lease/430388/1/1/status": remote error: tls: bad certificate`

Any ideas how I can resolve? Many thanks!

**Comment by blockTokenTech** [comment]
I've restarted docker using a differnt home address instead of pointing at the home address of my akash installation and it seems to work now

**Comment by tombeynon** [comment]
Thank you! I've definitely seen this before when using an existing config. I haven't worked out the cause yet but the above logs will be really useful. Possibly something to do with how the certificate is encrypted..

I'll update here if/when I solve it either way 👍🏻
