### ISSUE TITLE
Error in manifest shows "Deployment requires 5000000uakt escrow" and navigates to wallet page

### ISSUE THREAD

**Issue by MbBrainz** [tombeynon/akash-deploy#6]
I edited the manifest and once I pressed update manifest, the docker logs gave an invalid manifest error, while the ui sent me to wallet page and displayed the "Deployment requires 5000000uakt escrow" error. 

Logs from docker:
[errorlog-akashdeployUI.pdf](https://github.com/tombeynon/akash-deploy/files/6836373/errorlog-akashdeployUI.pdf)

**Comment by tombeynon** [comment]
Couple of issues here.

1. Akash has issues with domain names with a dash in them. This is incorrect validation but it's not something we can work around. I have raised an issue for this here: https://github.com/ovrclk/akash/issues/1326
2. You don't have enough balance for a _new_ deployment, hence the 5000000uakt required error. Looking at the logs you provided you had 4.975 AKT.

**Comment by MbBrainz** [comment]
1. - > Interesting! I've been corresponding with Jerome Berkshire and he managed to make it work for maurits-bos.me . www.maurits.bos.me is still not working though..
2. Yes thats what the site says, however i already have a deployment running. This was the one i pressed "edit" for. So the error shown there is also incorrect

**Comment by tombeynon** [comment]
1. Cool I've been chatting to Jerome - very strange about the validation there, but I'm sure it's all related. 
2. AH I see the issue. I've just pushed an update which will redirect to the correct place if updating a deployment fails. You should be able to update to latest version shortly with `docker pull tombeynon/akash-deploy`

**Comment by MbBrainz** [comment]
Nice! Glad you found it
